[package]
name = "RustDylib"
version = "0.1.0"
edition = "2021"
authors = ["Felipe Noronha <felipenoris@gmail.com>"]
build="build/build.rs"

[dependencies]

[lib]
name = "rustdylib"
crate-type = ["staticlib", "cdylib"]

[build-dependencies]
cbindgen = "0.23"
